### ISSUE TITLE
Plugin lets app crash

### ISSUE THREAD

**Issue by SimonIT** [rekire/autologin_plugin#3]
I don't know the reason for the crash, but it crashed multiple times by clicking on the button for not selecting an email address from the list and once after clicking on the save button I added in #1.

```java
E/AndroidRuntime( 8501): FATAL EXCEPTION: main
E/AndroidRuntime( 8501): Process: de.wbtsolutions.openproject_app, PID: 8501
E/AndroidRuntime( 8501): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=48233, result=-1, data=null} to activity {de.wbtsolutions.openproject_app/de.wbtsolutions.openproject_app.MainActivity}: java.util.ConcurrentModificationException
E/AndroidRuntime( 8501): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
E/AndroidRuntime( 8501): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
E/AndroidRuntime( 8501): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 8501): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 8501): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 8501): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/AndroidRuntime( 8501): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 8501): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 8501): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 8501): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8501): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 8501): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime( 8501): Caused by: java.util.ConcurrentModificationException
E/AndroidRuntime( 8501): 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
E/AndroidRuntime( 8501): 	at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
E/AndroidRuntime( 8501): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:689)
E/AndroidRuntime( 8501): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime( 8501): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:597)
E/AndroidRuntime( 8501): 	at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:699)
E/AndroidRuntime( 8501): 	at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:510)
E/AndroidRuntime( 8501): 	at android.app.Activity.dispatchActivityResult(Activity.java:8110)
E/AndroidRuntime( 8501): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
E/AndroidRuntime( 8501): 	... 11 more
I/Process ( 8501): Sending signal. PID: 8501 SIG: 9

```

**Comment by rekire** [comment]
I observed this bug too. It is an issue out of my view of the flutter framework I was able to confirm this issue. Basically I'm removing my observer which is breaking the iterator of the flutter implementation of the event handling. I found no workaround yet, but I will do my best this week.

**Comment by SimonIT** [comment]
In my opinion this bug has the highest priority. I wouldn't deploy my app with this plugin as long it can crash the whole app. It would destroy the whole user experience.

Is it necessary to remove the observer? My idea would be to let it attached if it breaks the plugin.
If it has to be removed, maybe you are doing it the wrong way?

I would help, but I'm absolute unfamiliar with Kotlin.

**Comment by rekire** [comment]
I cannot reproduce the issue right now. Can you please try to add for your flutter activity in your manifest this `meta-data` tag?

    <meta-data android:name="flutterEmbedding" android:value="2"/>

As sample I'm using this:

    <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data android:name="flutterEmbedding" android:value="2"/>

**Comment by SimonIT** [comment]
Is already there. Is default added by the project generator.

https://github.com/wbt-solutions/openproject_app/blob/018504aa46cef755ce9c60d39625ab285eb46047/android/app/src/main/AndroidManifest.xml#L46-L48

This is by the way the branch, where I tried the implementation and the exceptions/crashes happend.
https://github.com/wbt-solutions/openproject_app/tree/basic-autologin-implementation

**Comment by rekire** [comment]
I run your app and canceled the account chooser by pressing the back key, but nothing happened. Can you tell me what steps you have to cause that crash?
I still believe you that you get a crash, since I can remember this bug, but as you know it is hard to fix bugs which you cannot reproduce

**Comment by rekire** [comment]
Okay I found the reason again in all details. Basically if there is an "Account Chooser" I need to wait for activity result. When I got the result I remove my observer to avoid getting the data twice and also reporing the date twice to the dart part.

The code is here:
https://github.com/rekire/autologin_plugin/blob/44292526d884c37418dc6ae2f7f26dbd197c0b39/android/src/main/kotlin/eu/rekisoft/flutter/autologin/LoginHelper.kt#L113 (current master)

The real issue is in the engine: https://github.com/flutter/engine/blob/025e2d82dda54af7f33a0d511bde47ec835593b1/shell/platform/android/io/flutter/embedding/engine/FlutterEnginePluginRegistry.java#L688

That loop prevents that I can modify the list of observers. Out of my view it should just exit the loop when any listener consumed the result. I will open a bug now since I found the current source of the issue.

**Comment by SimonIT** [comment]
Thank you for finding the problem. Shouldn't be a fix straightforward? Stackoverflow suggests using iterators https://stackoverflow.com/a/18448699/7912520

**Comment by rekire** [comment]
No that is not the solution, that is causing the problem. It is a bit tricky: The iterator is keeping its position in memory and when I remove my listener the size has changed and the exception will be thown. Check the code e.g. here: http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/HashMap.java#l1428

**Comment by rekire** [comment]
FYI: Pull request on the flutter engine is open now

**Comment by SimonIT** [comment]
Thank you, I'm following the other issue and the PR

**Comment by rekire** [comment]
If you change the flutter channel to master the bug is fixed. I'll leave a note when I found out that it is on other channels too

**Comment by SimonIT** [comment]
Thank you for this massive work

**Comment by SimonIT** [comment]
Do you know on which channel the fix is?

**Comment by rekire** [comment]
It is a bit tricky to find that out. https://github.com/flutter/flutter/blob/beta/bin/internal/engine.version this file contains the git hash of the flutter engine which is used by the beta channel of flutter.

Right now the hash is `9d5b21729ff53dbf8eadd8bc97e0e30d77abec95`.

When I check the patched file with this commit:
https://github.com/flutter/engine/blob/9d5b21729ff53dbf8eadd8bc97e0e30d77abec95/shell/platform/android/io/flutter/embedding/engine/FlutterEnginePluginRegistry.java#L688-L692

Then I don't see the change there yet. Might be that PR was not cherry picked since I forgot to close a ticket.
