### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by SimonIT** [rekire/autologin_plugin#6]
There is an experimental web api for storing credentials:
https://developer.mozilla.org/en-US/docs/Web/API/Credential_Management_API

**Comment by rekire** [comment]
There is also an implementation for chrome: https://developers.google.com/web/updates/2016/04/credential-management-api
However I have no idea right now how to support websites from a plugin.

BTW: I also tried to find out if there is something similar on FireOS (the Amazon's Android Fork), but it seems that Amazon has no similar API

**Comment by SimonIT** [comment]
It's the same API, but documented by google. I will take a look at it how to integrate it

**Comment by rekire** [comment]
Ah great, I had that bookmark from a former research. Might be related that `autocomplete` attribute from apple: https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element

**Comment by SimonIT** [comment]
I found this kinda official tutorial how to create a web plugin: https://medium.com/flutter/how-to-write-a-flutter-web-plugin-5e26c689ea1

The thing is, web needs an additional sdk under the dependencies:
```
  flutter_web_plugins:
    sdk: flutter
```

I think with adding this to the main project we would force potential users to install the web sdk. To avoid it, they are creating an individual package only for web. https://medium.com/flutter/how-to-write-a-flutter-web-plugin-part-2-afdddb69ece6 This would be also needed if the windows own credentials manager (yes, it has one [here](https://docs.microsoft.com/en-us/windows/win32/secauthn/credentials-management))

By the way, the credentials api can be accessed easily via `html.window.navigator.credentials` inside the dart file for the web part.

**Comment by SimonIT** [comment]
Do you mind refactoring the project a bit for the federated plugins? I would make then the PR for web

**Comment by rekire** [comment]
Thank you for reminding me to change the structure I totally forgot about it.

**Comment by rekire** [comment]
If I understand that correctly then I don't need to change the structure anymore. I just created a stub where real implementation is still missing, but this is a start. By the way sorry for the huge delays, but this is a weekend project and I have not sooo much time
