### ISSUE TITLE
Possibility to set under which account credentials are saved

### ISSUE THREAD

**Issue by SimonIT** [rekire/autologin_plugin#7]
If I'm signed in with multiple Google accounts on my device I would like to have the possibility to save for example my works login under the works account and my private ones under my private account.

Referring to this https://developers.google.com/android/reference/com/google/android/gms/auth/api/credentials/package-summary, there seem to be `setAccountName` for archiving this. There would be also a method needed to get all available accounts to let the user choose the preferred one

**Comment by rekire** [comment]
I'll check this when the iOS implementation works

**Comment by rekire** [comment]
I'm thinking about how to implement this. I would implement this as a property map or something like that. I would use as key something like `"preferedGoogleAccount"`. This might be helpful for the JavaScript implementation too. There you could choose or at least read the selected implementation of the "Provider". What do you think about it?

**Comment by rekire** [comment]
I migrated to the credential manager API so this change is not possible anymore
